[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qplotly"
version = "0.1.0"
description = "A matplotlib-like interface for Plotly"
requires-python = ">=3.9"
dependencies = [
    "plotly",
    "numpy",
]
